[changelog]
commit_parsers = [
    { message = "^feat", group = "added" },
    { message = "^fix", group = "fixed" },
    { message = "^perf", group = "performance" },
    { message = "^refactor", group = "changed" },
    { message = '^chore(?:\([^)]*\))?!', group = "changed" },
    { message = "^docs", group = "documentation" },
    { message = "^security", group = "security" },
    { message = "^(build|chore|style)", group = "maintenance" },
    { message = "^(ci|test)", skip = true },
    { message = "^.*", skip = true },
]
