[package]
name = "delta-arrow-reader-python"
version.workspace = true
edition = "2024"
rust-version = "1.94"
license-file = "../../LICENSE"
repository = "https://github.com/mag1cfrog/delta-arrow-reader"
description = "Python bindings for the read-only Delta Lake to Apache Arrow reader"
publish = false

[lib]
name = "delta_arrow_reader"
crate-type = ["cdylib"]

[dependencies]
arrow = { version = "58.3.0", features = ["ffi"] }
delta-arrow-reader = { version = "0.6.2", path = "../.." }
pyo3 = { version = "0.29", features = ["abi3-py310"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
