[package]
name = "delta-arrow-reader-cli"
version.workspace = true
edition = "2024"
rust-version = "1.94"
license-file = "../../LICENSE"
repository = "https://github.com/mag1cfrog/delta-arrow-reader"
description = "Command-line reading of Delta Lake tables"
publish = false

[[bin]]
name = "dar"
path = "src/main.rs"

[dependencies]
arrow = "58.3.0"
arrow-schema = { version = "58.3.0", features = ["serde"] }
clap = { version = "4", default-features = false, features = ["derive", "std", "help", "usage"] }
delta-arrow-reader = { path = "../.." }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
snafu = "0.9"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time"] }
